# Generated by Django 4.2.5 on 2023-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_appuser_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="area",
            field=models.TextField(default="Select City", max_length=100),
        ),
    ]
