# Generated by Django 4.2.5 on 2023-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_appuser_gender_alter_appuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
