# Generated by Django 4.2.5 on 2023-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_alter_appuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="phone_number",
            field=models.IntegerField(default=0),
        ),
    ]
