# Generated by Django 4.2.5 on 2023-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_appuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="area",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
