# Generated by Django 4.2.5 on 2023-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_alter_appuser_area_alter_appuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemname", models.CharField(default="ItemName", max_length=50)),
                ("price", models.CharField(default="Price", max_length=4)),
                ("decription", models.CharField(default="Description", max_length=300)),
                ("ingridents", models.CharField(default="Ingridents", max_length=300)),
                ("itemtype", models.CharField(default="type", max_length=200)),
            ],
        ),
    ]
