# Generated by Django 4.2.5 on 2023-09-20 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_food"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="decription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="food",
            old_name="ingridents",
            new_name="ingridients",
        ),
    ]
