# Generated by Django 4.2.5 on 2023-09-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0011_rename_decription_food_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="username",
            field=models.CharField(default="ItemName", max_length=150),
        ),
    ]
