# Generated by Django 4.2.5 on 2023-09-20 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_food_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="food",
            new_name="FoodItems",
        ),
    ]
