# Generated by Django 4.2.5 on 2023-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_rename_food_fooditems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditems",
            name="username",
            field=models.CharField(default="UserName", max_length=150),
        ),
    ]
