# Generated by Django 4.2.5 on 2023-09-20 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_alter_fooditems_itemname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditems",
            old_name="ingridients",
            new_name="ingridents",
        ),
    ]
