# Generated by Django 4.2.5 on 2023-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_rename_ingridients_fooditems_ingridents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditems",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="fooditems",
            name="ingridents",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="fooditems",
            name="itemname",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="fooditems",
            name="itemtype",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="fooditems",
            name="price",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="fooditems",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
