# Generated by Django 4.2.5 on 2023-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0017_alter_fooditems_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("itemname", models.CharField(max_length=50, unique=True)),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
