# Generated by Django 4.2.5 on 2023-09-21 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0018_itemlogs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemLogs",
        ),
    ]
