# Generated by Django 4.2.5 on 2023-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0019_delete_itemlogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("itemname", models.CharField(max_length=50, unique=True)),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
