# Generated by Django 4.2.5 on 2023-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
