# Generated by Django 4.2.5 on 2023-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0021_cart_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("totalPrice", models.BigIntegerField(default=0)),
                ("items", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
