# Generated by Django 4.2.5 on 2023-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0022_orders_alter_cart_amount_alter_cart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
